quiz_4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from quiz_4.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts_app.urls')),
    path('quizs/', include('quiz_app.urls')),
    path('admins/', include('admins_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz_app/urls.py
from django.urls import path

from quiz_app.views import HomeView, StartQuiz, ProcessQuiz

app_name = 'quiz'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('start/', StartQuiz.as_view(), name='start_quiz'),
    path('process/<int:id>', ProcessQuiz.as_view(), name='process_quiz'),
]

quiz_app/models.py
from django.contrib.auth.models import User
from django.db import models

from language_app.utils import choices as lang_choices
# Create your models here.
from quiz_4.models import Auditable
from quiz_app.utils import level_choices, category_choices


class Category(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100, unique=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.code = self.name.upper().replace(" ", "_")
        super().save(force_insert, force_update, using, update_fields)

    class Meta:
        db_table = 'question_category'


class Level(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100, unique=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.code = self.name.upper().replace(" ", "_")
        super().save(force_insert, force_update, using, update_fields)

    class Meta:
        db_table = 'question_level'


class Question(Auditable):
    question = models.CharField(max_length=300)
    category = models.CharField(max_length=100, choices=category_choices())
    level = models.CharField(max_length=100, choices=level_choices())
    lang = models.CharField(max_length=100, choices=lang_choices())
    valid = models.BooleanField(default=False)

    def __str__(self):
        return self.question


class QuestionOptions(Auditable):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=300)
    right = models.BooleanField(default=False)


class Quiz(models.Model):
    category = models.CharField(max_length=50, choices=category_choices())
    level = models.CharField(max_length=50, choices=level_choices())
    lang = models.CharField(max_length=50, choices=lang_choices())
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(null=True, default=None)


class QuizOptions(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, models.CASCADE)
    check = models.BooleanField(default=False)
    before_id = models.BigIntegerField(default=None, null=True)

quiz_app/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

# Create your views here.
from language_app.models import Language
from quiz_app.models import Category, Question, Level, Quiz, QuizOptions, QuestionOptions


class HomeView(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        context = []
        categories = Category.objects.all()
        for category in categories:
            category_code = category.code
            count = Question.objects.filter(category=category_code).count()
            data = {
                "name": category.name,
                "code": category.code,
                "count": count,
            }
            context.append(data)
        return render(request, self.template_name, {
            'context': context,
            'categories': categories,
            'levels': Level.objects.all(),
            'langs': Language.objects.all()
        })


class StartQuiz(TemplateView):
    template_name = 'quiz.html'

    def _allowed_methods(self):
        return ['POST', ]

    def post(self, request, *args, **kwargs):
        lang: str = request.POST.get('lang')
        category: str = request.POST.get('category')
        level: str = request.POST.get('level')
        count: int = int(request.POST.get('count'))
        quiz = Quiz.objects.filter(Q(created_by=request.user) & Q(finished_at=None)).first()
        if not quiz:
            questions = Question.objects.filter(
                Q(category__startswith=(category or '')) &
                Q(level__startswith=(level or '')) &
                Q(lang__startswith=(lang or ''))
            ).all()[:count]

            quiz = Quiz(category=category, level=level, lang=lang, created_by=request.user)
            quiz.save()
            before_id = None
            for question in questions:
                qo = QuizOptions(question=question, quiz=quiz, before_id=before_id)
                qo.save()
                before_id = qo.id
        else:
            messages.error(request, "You Already have Non Completed Quiz please complete it ?")
        quiz_option = QuizOptions.objects.filter(Q(quiz=quiz)).order_by("id").first()
        return redirect('quiz:process_quiz', quiz_option.id)


class ProcessQuiz(TemplateView):
    template_name = 'process_quiz.html'

    def get(self, request, *args, **kwargs):
        quiz_option_id: int = int(kwargs['id'])
        qo = QuizOptions.objects.filter(before_id=quiz_option_id)
        question_id = qo.question_id
        options = QuestionOptions.objects.filter(question_id=question_id).all()
        return render(request, self.template_name, {
            'question': qo.question.question,
            'next_id': 12,
            'options': options
        })

    def post(self, request, *args, **kwargs):
        pass

quiz_app/templates/index.html
{% extends 'layout.html' %}

{% block title %}
    Home Page
{% endblock %}
{% block content %}
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Start Quiz
    </button>
    <div class="row">
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Please Choose needed infos</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{% url 'quiz:start_quiz' %}">
                            {% csrf_token %}
                            <div class="m-2">
                                <select class="form-select" name="lang" aria-label="Default select example">
                                    {% for lang in langs %}
                                        {% if lang.code == user.employee.language %}
                                            <option selected value="{{ lang.code }}">{{ lang.name }}</option>
                                        {% else %}
                                            <option value="{{ lang.code }}">{{ lang.name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="m-2">
                                <select class="form-select" name="category" aria-label="Default select example">
                                    {% for category in categories %}
                                        {% if category.code == 'easy' %}
                                            <option selected
                                                    value="{{ category.code }}">{{ category.name }}</option>
                                        {% else %}
                                            <option value="{{ category.code }}">{{ category.name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="m-2">
                                <select class="form-select" name="level" aria-label="Default select example">
                                    {% for level in levels %}
                                        {% if level.code == 'easy' %}
                                            <option selected value="{{ level.code }}">{{ level.name }}</option>
                                        {% else %}
                                            <option value="{{ level.code }}">{{ level.name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="m-2">
                                <select class="form-select" name="count" aria-label="Default select example">
                                    <option value="5">5</option>
                                    <option value="10">10</option>
                                    <option value="15">15</option>
                                    <option value="20">20</option>
                                </select>
                            </div>
                            <input type="submit" class="btn btn-success" value="start">
                        </form>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="offset-3 col-6">
            {% for data in context %}
                <p>{{ data.name }} {{ data.count }}</p>
            {% endfor %}

        </div>
    </div>
{% endblock %}

quiz_app/templates/process_quiz.html
{% extends 'layout.html' %}



{% block title %}
    Solve Quiz
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="offset-3 col-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-header">
                        {{ question }}
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for option in options %}
                            <li class="list-group-item">{{ option.answer }}</li>
                        {% endfor %}
                    </ul>
                    <div class="card-footer bg-light align-center">
{#                        <a href="{{ current_id }}" class="btn btn-success">Back</a>#}
                        <a href="{{ current_id|add:1 }}" class="btn btn-success">Next</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}