accounts_app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from accounts_app.views import LoginView, RegisterView

app_name = 'auth'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

admins_app/urls.py
from django.urls import path

from admins_app.views import (HomeView,
                              CreateQuestionView,
                              CreateQuestionOptionView,
                              QuestionListView,
                              CreateLevelView, QuizUpdate, QuizDelete)

app_name = 'admins'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create/', CreateQuestionView.as_view(), name='create_question'),
    path('list/', QuestionListView.as_view(), name='question_list'),
    path('add_option/<int:question_id>', CreateQuestionOptionView.as_view(), name='add_option'),
    path('create/level/', CreateLevelView.as_view(), name='create_level'),
    path('quiz-update/<int:pk>/', QuizUpdate.as_view(), name='quiz-update'),
    path('quiz-delete/<int:pk>/', QuizDelete.as_view(), name='quiz-delete'),
]

quiz_4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from quiz_4.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts_app.urls')),
    path('quizs/', include('quiz_app.urls')),
    path('admins/', include('admins_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz_app/urls.py
from django.urls import path

from quiz_app.views import HomeView, StartQuiz, ProcessQuiz

app_name = 'quiz'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('start/', StartQuiz.as_view(), name='start_quiz'),
    path('process/<int:id>', ProcessQuiz.as_view(), name='process_quiz'),
]

admins_app/models.py
from django.db import models

# Create your models here.

admins_app/forms.py
from django import forms

from language_app.utils import choices as lang_choices
from quiz_app.utils import category_choices, level_choices


class CreateQuestionForm(forms.Form):
    category = forms.CharField(label="Category",
                               widget=forms.Select(attrs={'class': 'form-control'}, choices=category_choices()))
    level = forms.CharField(label="Level",
                            widget=forms.Select(attrs={'class': 'form-control'}, choices=level_choices()))
    lang = forms.CharField(label="Language",
                           widget=forms.Select(attrs={'class': 'form-control'}, choices=lang_choices()))
    question = forms.CharField(label='Question', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))



class CreateQuestionOptionForm(forms.Form):
    option = forms.CharField(label="Option", widget=forms.TextInput(attrs={'class': 'form-control'}))
    right = forms.ChoiceField(label="Right ?", widget=forms.CheckboxInput(), choices=[('yes', "Yes"), ('no', 'No')])


class CreateLevelForm(forms.Form):
    level = forms.CharField(label="Level", widget=forms.TextInput(attrs={'class': 'form-control'}))

admins_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView

from admins_app.forms import CreateQuestionForm, CreateQuestionOptionForm, CreateLevelForm
from admins_app.service import create_question, create_option, create_level
# Create your views here.
from language_app.models import Language
from language_app.utils import choices as lang_choices
from quiz_app.models import Question, Category, Level, QuestionOptions
from quiz_app.utils import level_choices, category_choices


# Commit by Javohir

class HomeView(TemplateView):
    template_name = 'admins_home.html'


class CreateQuestionView(TemplateView):
    template_name = 'question/create_question.html'

    def get(self, request, *args, **kwargs):
        values = {
            "level": level_choices(),
            "category": category_choices(),
            "lang": lang_choices(),
        }
        form = CreateQuestionForm(data=values)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = CreateQuestionForm(request.POST)
        if form.is_valid():
            question = create_question(form, request.user)
            return redirect('admins:add_option', question.id)
        return render(request, self.template_name, {'form': form})


class CreateQuestionOptionView(TemplateView):
    template_name = 'option/add_option.html'

    def get(self, request, *args, **kwargs):
        form = CreateQuestionOptionForm()
        question = Question.objects.get(pk=int(kwargs['question_id']))
        options = QuestionOptions.objects.filter(question=question)
        return render(request, self.template_name, {'form': form, 'question': question, 'options': options})

    def post(self, request, *args, **kwargs):
        form = CreateQuestionOptionForm(request.POST)
        create_option(form, kwargs['question_id'], request.user)
        return redirect("admins:add_option", kwargs['question_id'])


class QuestionListView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'question/question_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        page_number = self.request.GET.get('page', 1)
        category_filter = self.request.GET.get('category_filter')
        level_filter = self.request.GET.get('level_filter')
        lang_filter = self.request.GET.get('lang_filter')
        search = self.request.GET.get('search')

        context = super().get_context_data(object_list=object_list, **kwargs)
        questions = self.model.objects.filter(
            Q(question__contains=(search or '')) &
            Q(category__startswith=(category_filter or '')) &
            Q(level__startswith=(level_filter or '')) &
            Q(lang__startswith=(lang_filter or ''))
        ).all()
        paginator = Paginator(questions, 5)
        page_obj = paginator.get_page(page_number)
        context['questions'] = page_obj
        context['categories'] = Category.objects.all()
        context['levels'] = Level.objects.all()
        context['langs'] = Language.objects.all()
        context['total'] = questions.count()

        return context


class CreateLevelView(TemplateView):
    template_name = 'level/create_level.html'

    def get(self, request, *args, **kwargs):
        form = CreateLevelForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = CreateLevelForm(request.POST)
        create_level(form)
        return redirect("admins:home")


class QuizUpdate(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['level', 'category', 'lang','question']
    template_name = 'question/update_questions.html'
    success_url = reverse_lazy('admins:question_list')
    # form_class = CreateQuestionForm


class QuizDelete(LoginRequiredMixin, DeleteView):
    model = Question
    context_object_name = 'question'
    template_name = 'question/question_confirm_delete.html'
    success_url = reverse_lazy('admins:question_list')

admins_app/templates/admins_home.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

admins_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
{% load mytags %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} </title>
    {#    {% block header_files %}#}
    {##}
    {#    {% endblock %}#}
    <style>

    </style>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body style="overflow-x: hidden">
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/"
                   class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
                    id="menu">
                    <li class="nav-item">
                        <a href="{% url 'quiz:index' %}" class="text-white nav-link align-middle px-0">Quiz</a>
                    </li>
                    <li>
                        <a href="#submenu1" data-bs-toggle="collapse" class="text-white nav-link px-0 align-middle">
                            Question </a>
                        <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="{% url 'admins:create_question' %}" class="nav-link text-white px-0">
                                    Create Question
                                </a>
                            </li>
                            <li class="w-100">
                                <a href="{% url 'admins:question_list' %}" class="nav-link text-white px-0">
                                    Question List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                            Level</a>
                        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="{% url 'admins:create_level' %}" class="nav-link  text-white px-0">Create Level</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>
                        <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span>
                        </a>
                    </li>
                </ul>
                <hr>
                {% if user.is_authenticated %}
                    <div class="dropdown pb-4">
                        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                           id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.employee.profile_image.path }}" alt="hugenerd" width="30" height="30"
                                 class="rounded-circle">
                            <span class="d-none d-sm-inline mx-1">loser</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                            <li><a class="dropdown-item" href="#">New project...</a></li>
                            <li><a class="dropdown-item" href="#">Settings</a></li>
                            <li><a class="dropdown-item" href="#">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'auth:logout' %}">Sign out</a></li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col py-3">
            <section>
                <div class="row">
                    <section class="offset-2 col-8">
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                    <div
                                            {% if message.tags %}
                                                class="alert alert-{{ message.tags }} alert-dismissible fade show"
                                                role="alert"
                                            {% endif %}
                                    >

                                        {{ message }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                                aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </section>
                </div>
            </section>
            <main>
                {% block content %}

                {% endblock %}
            </main>
        </div>
    </div>
</div>
<footer>

</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>