accounts_app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from accounts_app.views import LoginView, RegisterView

app_name = 'auth'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

admins_app/urls.py
from django.urls import path

from admins_app.views import (HomeView,
                              CreateQuestionView,
                              CreateQuestionOptionView,
                              QuestionListView,
                              CreateLevelView, QuizUpdate, QuizDelete)

app_name = 'admins'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create/', CreateQuestionView.as_view(), name='create_question'),
    path('list/', QuestionListView.as_view(), name='question_list'),
    path('add_option/<int:question_id>', CreateQuestionOptionView.as_view(), name='add_option'),
    path('create/level/', CreateLevelView.as_view(), name='create_level'),
    path('quiz-update/<int:pk>/', QuizUpdate.as_view(), name='quiz-update'),
    path('quiz-delete/<int:pk>/', QuizDelete.as_view(), name='quiz-delete'),
]

quiz_4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from quiz_4.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts_app.urls')),
    path('quizs/', include('quiz_app.urls')),
    path('admins/', include('admins_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz_app/urls.py
from django.urls import path

from quiz_app.views import HomeView, StartQuiz, ProcessQuiz

app_name = 'quiz'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('start/', StartQuiz.as_view(), name='start_quiz'),
    path('process/<int:id>', ProcessQuiz.as_view(), name='process_quiz'),
]

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home Page
{% endblock %}
{% block content %}
    <h1>{{ emoji }}</h1>
    {% if user.is_authenticated %}
        <h1>Welcome {{ user.username }}</h1>
    {% else %}
        <h2>Please Sign</h2>
    {% endif %}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body style="overflow-x: hidden">
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid offset-1 col-10">
            <a class="navbar-brand" href="{% url 'quiz:index' %}">{% trans 'MyQuiz' %}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">{% trans 'Home' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'admins:home' %}">Admin</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}

                        <div class="dropdown dropstart">
                            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton2"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                {{ user.first_name }} {{ user.last_name }}
                            </button>
                            <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="dropdownMenuButton2">
                                <li><a class="dropdown-item active" style="padding:0"
                                       href="{{ user.employee.profile_image.path }}">
                                    <img width="200" height="160" src="{{ user.employee.profile_image.path }}"
                                         alt="user.employee.profile_image.original_name">
                                </a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'auth:logout' %}">{% trans 'Logout' %}</a>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <a class="btn btn-outline-success" href="{% url 'auth:login' %}">Login</a>
                        <a class="btn btn-outline-success" href="{% url 'auth:register' %}">Register</a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<section class="container">
    <div class="row">
        <section class="offset-2 col-8">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <div
                                {% if message.tags %}
                                    class="alert alert-{{ message.tags }} alert-dismissible fade show"
                                    role="alert"
                                {% endif %}
                        >

                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                </ul>
            {% endif %}
        </section>
    </div>
</section>
<main>
    {% block content %}

    {% endblock %}
</main>
<footer>

</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>