admins_app/urls.py
from django.urls import path

from admins_app.views import (HomeView,
                              CreateQuestionView,
                              CreateQuestionOptionView,
                              QuestionListView,
                              CreateLevelView, QuizUpdate, QuizDelete)

app_name = 'admins'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create/', CreateQuestionView.as_view(), name='create_question'),
    path('list/', QuestionListView.as_view(), name='question_list'),
    path('add_option/<int:question_id>', CreateQuestionOptionView.as_view(), name='add_option'),
    path('create/level/', CreateLevelView.as_view(), name='create_level'),
    path('quiz-update/<int:pk>/', QuizUpdate.as_view(), name='quiz-update'),
    path('quiz-delete/<int:pk>/', QuizDelete.as_view(), name='quiz-delete'),
]

quiz_4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from quiz_4.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts_app.urls')),
    path('quizs/', include('quiz_app.urls')),
    path('admins/', include('admins_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admins_app/models.py
from django.db import models

# Create your models here.

admins_app/forms.py
from django import forms

from language_app.utils import choices as lang_choices
from quiz_app.utils import category_choices, level_choices


class CreateQuestionForm(forms.Form):
    category = forms.CharField(label="Category",
                               widget=forms.Select(attrs={'class': 'form-control'}, choices=category_choices()))
    level = forms.CharField(label="Level",
                            widget=forms.Select(attrs={'class': 'form-control'}, choices=level_choices()))
    lang = forms.CharField(label="Language",
                           widget=forms.Select(attrs={'class': 'form-control'}, choices=lang_choices()))
    question = forms.CharField(label='Question', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))



class CreateQuestionOptionForm(forms.Form):
    option = forms.CharField(label="Option", widget=forms.TextInput(attrs={'class': 'form-control'}))
    right = forms.ChoiceField(label="Right ?", widget=forms.CheckboxInput(), choices=[('yes', "Yes"), ('no', 'No')])


class CreateLevelForm(forms.Form):
    level = forms.CharField(label="Level", widget=forms.TextInput(attrs={'class': 'form-control'}))

admins_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView

from admins_app.forms import CreateQuestionForm, CreateQuestionOptionForm, CreateLevelForm
from admins_app.service import create_question, create_option, create_level
# Create your views here.
from language_app.models import Language
from language_app.utils import choices as lang_choices
from quiz_app.models import Question, Category, Level, QuestionOptions
from quiz_app.utils import level_choices, category_choices


# Commit by Javohir

class HomeView(TemplateView):
    template_name = 'admins_home.html'


class CreateQuestionView(TemplateView):
    template_name = 'question/create_question.html'

    def get(self, request, *args, **kwargs):
        values = {
            "level": level_choices(),
            "category": category_choices(),
            "lang": lang_choices(),
        }
        form = CreateQuestionForm(data=values)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = CreateQuestionForm(request.POST)
        if form.is_valid():
            question = create_question(form, request.user)
            return redirect('admins:add_option', question.id)
        return render(request, self.template_name, {'form': form})


class CreateQuestionOptionView(TemplateView):
    template_name = 'option/add_option.html'

    def get(self, request, *args, **kwargs):
        form = CreateQuestionOptionForm()
        question = Question.objects.get(pk=int(kwargs['question_id']))
        options = QuestionOptions.objects.filter(question=question)
        return render(request, self.template_name, {'form': form, 'question': question, 'options': options})

    def post(self, request, *args, **kwargs):
        form = CreateQuestionOptionForm(request.POST)
        create_option(form, kwargs['question_id'], request.user)
        return redirect("admins:add_option", kwargs['question_id'])


class QuestionListView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'question/question_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        page_number = self.request.GET.get('page', 1)
        category_filter = self.request.GET.get('category_filter')
        level_filter = self.request.GET.get('level_filter')
        lang_filter = self.request.GET.get('lang_filter')
        search = self.request.GET.get('search')

        context = super().get_context_data(object_list=object_list, **kwargs)
        questions = self.model.objects.filter(
            Q(question__contains=(search or '')) &
            Q(category__startswith=(category_filter or '')) &
            Q(level__startswith=(level_filter or '')) &
            Q(lang__startswith=(lang_filter or ''))
        ).all()
        paginator = Paginator(questions, 5)
        page_obj = paginator.get_page(page_number)
        context['questions'] = page_obj
        context['categories'] = Category.objects.all()
        context['levels'] = Level.objects.all()
        context['langs'] = Language.objects.all()
        context['total'] = questions.count()

        return context


class CreateLevelView(TemplateView):
    template_name = 'level/create_level.html'

    def get(self, request, *args, **kwargs):
        form = CreateLevelForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = CreateLevelForm(request.POST)
        create_level(form)
        return redirect("admins:home")


class QuizUpdate(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['level', 'category', 'lang','question']
    template_name = 'question/update_questions.html'
    success_url = reverse_lazy('admins:question_list')
    # form_class = CreateQuestionForm


class QuizDelete(LoginRequiredMixin, DeleteView):
    model = Question
    context_object_name = 'question'
    template_name = 'question/question_confirm_delete.html'
    success_url = reverse_lazy('admins:question_list')

admins_app/templates/question/create_question.html
{% extends 'base.html' %}
{% load mytags %}
{% block title %}
    Create Question
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-10 offset-1">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="{{ form.category.id_for_label }}" class="form-label">{{ form.category.label }}</label>
                    {{ form.category }}
                </div>
                <div class="mb-3">
                    <label for="{{ form.level.id_for_label }}" class="form-label">{{ form.level.label }}</label>
                    {{ form.level }}
                </div>
                <div class="mb-3">
                    <label for="{{ form.lang.id_for_label }}" class="form-label">{{ form.lang.label }}</label>
                    {{ form.lang }}
                </div>
                <div class="mb-3">
                    <label for="{{ form.question.id_for_label }}" class="form-label">{{ form.question.label }}</label>
                    {{ form.question }}
                </div>
                <input type="submit" class="btn btn-success" value="Proceed">
            </form>
        </div>
    </div>
{% endblock %}

admins_app/templates/question/question_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
    Delete question
{% endblock title %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure want to delete this question?</p>
        <h3>
            {{ question }}
        </h3>

        <a href="{% url 'admins:question_list' %}" class="btn btn-primary">Go back</a>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

admins_app/templates/question/question_list.html
{% extends 'base.html' %}
{% load mytags %}
{% block title %}
    Question List
{% endblock %}


{% block content %}
    <p class="h4">{{ total }}</p>
    <div class="row">
        <form>
            <div class="offset-1 col-10">
                <div class="row align-items-center">
                    <div class="col-3">
                        <input type="text" class="form-control" name="search" id="search" placeholder="search...">
                    </div>
                    <div class="col-2">
                        <select name="category_filter" class="form-control" id="category_filter">
                            <option value="" hidden>Category</option>
                            {% for category in categories %}
                                <option value="{{ category.code }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-2">
                        <select name="level_filter" class="form-control" id="level_filter">
                            <option value="" hidden>Level</option>
                            {% for level in levels %}
                                <option value="{{ level.code }}">{{ level.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-2">
                        <select name="lang_filter" class="form-control" id="lang_filter">
                            <option value="" hidden>Language</option>
                            {% for lang in langs %}
                                <option value="{{ lang.code }}">{{ lang.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-1">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Question</th>
            <th scope="col">Category</th>
            <th scope="col">Level</th>
            <th scope="col">Lang</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for question in questions %}
            <tr>
                <th scope="row"> {{ questions.number|gen_id:forloop.counter }}</th>
                <td>{{ question.question|slice:100 }}...</td>
                <td>{{ question.category }}</td>
                <td>{{ question.level }}</td>
                <td>{{ question.lang }}</td>
                <td>
                    <a class="btn btn-secondary" href="{% url 'admins:quiz-update' question.id %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'admins:quiz-delete' question.id %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if questions.paginator.page_range %}
        <nav aria-label="Page navigation example">

            <ul class="pagination">
                {% if questions.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ questions.previous_page_number }}"
                           aria-label="Previous">
                            Previous
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous">
                            Previous
                        </a>
                    </li>
                {% endif %}


                {% for page in questions.paginator.page_range %}
                    {% if questions.number == page %}
                        <li class="page-item active">
                            <a aria-current="page" class="page-link" href="?page={{ page }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if questions.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ questions.next_page_number }}" aria-label="Next">
                            Next
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Next">
                            Next
                        </a>
                    </li>
                {% endif %}
            </ul>

        </nav>
    {% endif %}
{% endblock %}

admins_app/templates/question/update_questions.html
{% extends 'base.html' %}
{% block title %}
    Update title
{% endblock title %}

{% block content %}
    <div class="row  update-question ">
        <div class="col-10 offset-1">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="{{ form.category.id_for_label }}" class="form-label">{{ form.category.label }}</label>
                    {{ form.category }}
                </div>
                <div class="mb-3">
                    <label for="{{ form.level.id_for_label }}" class="form-label">{{ form.level.label }}</label>
                    {{ form.level }}
                </div>
                <div class="mb-3">
                    <label for="{{ form.lang.id_for_label }}" class="form-label">{{ form.lang.label }}</label>
                    {{ form.lang }}
                </div>
                <div class="mb-3">
                    <label for="{{ form.question.id_for_label }}" class="form-label">{{ form.question.label }}</label>
                    {{ form.question }}
                </div>
                <a href="{% url 'admins:question_list' %}" class="btn btn-primary">Go back</a>
                <input type="submit" value="Update" class="btn btn-success " style="width: 100px;margin: 20px auto">
            </form>
        </div>
    </div>
{% endblock content %}